//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ObesityCare.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ObesityCare_BMI_Entities : DbContext
    {
        public ObesityCare_BMI_Entities()
            : base("name=ObesityCare_BMI_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BOY_BMI> BOY_BMI { get; set; }
        public virtual DbSet<GIRL_BMI> GIRL_BMI { get; set; }

    }
}
