//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ObesityCare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIRL_BMI
    {
        public decimal Age_in_months { get; set; }
        public decimal third_Percentile { get; set; }
        public decimal fifth_Percentile { get; set; }
        public decimal tenth_Percentile { get; set; }
        public decimal twenty_fifth_Percentile { get; set; }
        public decimal fiftieth_Percentile { get; set; }
        public decimal seventy_fifth_Percentile { get; set; }
        public decimal eightieth_Percentile { get; set; }
        public decimal ninetieth_Percentile { get; set; }
        public decimal ninety_fifth_Percentile { get; set; }
        public decimal ninety_seventh_Percentile { get; set; }
    }
}
