//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ObesityCare.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Record
    {
        public int Id { get; set; }
        [Display(Name= "Activity")]
        public string Name { get; set; }
        public string Location { get; set; }

        public string Duration { get; set; }
        [Display(Name = "Star Exchange")]
        public int Star { get; set; }
        public string UserId { get; set; }
    }
}
